title: Jacqueline Lee
description: Jacqueline Lee's Projects and Background
author: Jacqueline Lee
theme: just-the-docs
color_scheme: custom-dark-theme

url: https://jacquelinekclee.github.io/new-portfolio
baseurl: /new-portfolio

search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Resume:
  - 'https://jacquelinekclee.github.io/new-portfolio/jacqueline_lee_resume_122023.pdf'
  LinkedIn:
    - 'https://www.linkedin.com/in/jacqueline-kc-lee/'
  Email Me:
    - 'mailto:jacquelinekclee'
  GitHub:
    - 'https://github.com/jacquelinekclee'

aux_links_new_tab: true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Collections for website data
collections:
  experiences:
    permalink: /:collection/:path/
    output: true
    order:
      - ibm.md
      - ballertv.md
      - bessemer.md
      - te.md
  # projects:
  # skills:
# Default layouts for each collection type

just-the-docs:
  collections:
    experiences:
      nav_fold: true
    
defaults:
  - scope:
      path: ''
      type: experiences
      
    values:
      layout: experience
      subpath: '/assets/company-logos/'

  # - scope:
  #     path: ''
  #     type: projects
  #   values:
  #     layout: project
  #     subpath: '/assets/project-images/'
  # - scope:
  #     path: ''
  #     type: skills
  #   values:
  #     layout: skill
  #     subpath: '/assets/skill-logos/'
 